databases:
  - name: rifa-db
    plan: free
    databaseName: rifa
    user: rifa_user

services:
  - type: web
    name: rifa-online
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    port: 80
    envVars:
      - key: BASE_URL
        sync: false
      - key: DB_SERVER
        fromDatabase:
          name: rifa-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: rifa-db
          property: port
      - key: DB_USERNAME
        fromDatabase:
          name: rifa-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: rifa-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: rifa-db
          property: database
