<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit0e19ee7ed74e9403f6e4a233e79e88c3
{
    public static $prefixLengthsPsr4 = array (
        'V' => 
        array (
            'VisualAppeal\\' => 13,
        ),
        'P' => 
        array (
            'Psr\\SimpleCache\\' => 16,
            'Psr\\Log\\' => 8,
        ),
        'M' => 
        array (
            'Monolog\\' => 8,
        ),
        'D' => 
        array (
            'Desarrolla2\\Cache\\' => 18,
        ),
        'C' => 
        array (
            'Composer\\Semver\\' => 16,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'VisualAppeal\\' => 
        array (
            0 => __DIR__ . '/..' . '/visualappeal/php-auto-update/src',
        ),
        'Psr\\SimpleCache\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/simple-cache/src',
        ),
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'Monolog\\' => 
        array (
            0 => __DIR__ . '/..' . '/monolog/monolog/src/Monolog',
        ),
        'Desarrolla2\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/desarrolla2/cache/src',
        ),
        'Composer\\Semver\\' => 
        array (
            0 => __DIR__ . '/..' . '/composer/semver/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit0e19ee7ed74e9403f6e4a233e79e88c3::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit0e19ee7ed74e9403f6e4a233e79e88c3::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit0e19ee7ed74e9403f6e4a233e79e88c3::$classMap;

        }, null, ClassLoader::class);
    }
}
